name: Auto Update README

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at 00:00 UTC
  workflow_dispatch:       # Let you trigger manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update README Date
        run: |
          current_date=$(date '+%Y-%m-%d %H:%M:%S')
          sed -i "s/{{date}}/$current_date/g" README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-action-bot@example.com"
          git config --local user.name "github-action-bot"
          git add README.md
          git commit -m "README updated at $current_date" || exit 0
          git push
